build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related prod APIs "
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "d4bfb4e353e9fe2ae8173f63cedd30a2c384b4bddf5072c0d68583ef1562a9fda7921307aa8e5d527d79522637faf732"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384
